[program:ludovicopratesi]
directory=/srv/apps/ludovicopratesi
command=/srv/apps/ludovicopratesi/bin/run_gunicorn.sh
user=deploy
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/srv/logs/ludovicopratesi-gunicorn.log
environment=PYTHONUNBUFFERED="1",DJANGO_SETTINGS_MODULE="www.settings.prod"
