[group:ludovicopratesi.it]
programs=gunicorn_ludovicopratesi.it

[program:gunicorn_ludovicopratesi.it]
command=/home/ludovicopratesi/.env/bin/gunicorn -c /home/ludovicopratesi/django/etc/gunicorn/www.py --error-log /home/ludovicopratesi/var/log/gunicorn.error.log www.wsgi
directory=/home/ludovicopratesi/django
user=ludovicopratesi
autostart=true
autorestart=true
redirect_stderr=true
environment=LANG="en_US.UTF-8",LC_ALL="en_US.UTF-8",LC_LANG="en_US.UTF-8"
stdout_logfile=/home/ludovicopratesi/var/log/supervisor.output.log ; stdout log path, NONE for none; default AUTO
stdout_logfile_maxbytes=1MB ; max # logfile bytes b4 rotation (default 50MB)
stderr_logfile=/home/ludovicopratesi/var/log/supervisor.error.log ; stdout log path, NONE for none; default AUTO
stderr_logfile_maxbytes=1MB ; max # logfile bytes b4 rotation (default 50MB)
