# Generated by Django 2.0.7 on 2018-07-07 04:40

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import frontend.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text="Nome dell'artista. Massimo 255 caratteri", max_length=255, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(help_text="Cognome dell'artista. Massimo 255 caratteri", max_length=255, verbose_name='last_name')),
            ],
            options={
                'verbose_name': 'artist',
                'verbose_name_plural': 'artists',
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='nome della mostra', max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text='nome della mostra sulla barra degli indirizzi(compilato automaticamente)', max_length=100, unique=True, verbose_name='slug')),
                ('excerpt_it', models.CharField(blank=True, default='', help_text='breve descrizione della mostra', max_length=255, null=True, verbose_name='excerpt_it')),
                ('description_it', tinymce.models.HTMLField(help_text='descrizione completa della mostra', verbose_name='description_it')),
                ('excerpt_en', models.CharField(blank=True, default='', help_text='breve descrizione della mostra(inglese)', max_length=255, null=True, verbose_name='excerpt_en')),
                ('description_en', tinymce.models.HTMLField(help_text='descrizione completa della mostra(inglese)', verbose_name='description_en')),
                ('address', models.CharField(help_text='Indirizzo della mostra', max_length=255, verbose_name='address')),
                ('begun_at', models.DateField(help_text='Data inizio mostra', verbose_name='begun_at')),
                ('ended_at', models.DateField(help_text='Data fine mostra', verbose_name='ended_at')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('authors', models.ManyToManyField(help_text='autori della mostra', to='frontend.Author', verbose_name='authors')),
            ],
            options={
                'verbose_name': 'exhibit',
                'verbose_name_plural': 'exhibits',
                'db_table': 'exhibit',
            },
        ),
        migrations.CreateModel(
            name='ExhibitImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', easy_thumbnails.fields.ThumbnailerImageField(help_text="Inserire il file dell'immagine", upload_to=frontend.models.get_image_path, verbose_name='Nome file')),
                ('is_thumbnail', models.BooleanField(default=False, help_text="Se selezionata l'immagine sarà la principale della mostra", verbose_name='immagine principale')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='frontend.Exhibit')),
            ],
            options={
                'verbose_name': 'exhibit_image',
                'verbose_name_plural': 'exhibit_images',
                'db_table': 'exhibit_image',
                'ordering': ['-is_thumbnail'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome Cv', max_length=255, verbose_name='title')),
                ('lang', models.CharField(choices=[('it', 'italiano'), ('en', 'english')], help_text='Linguaggio utilizzato nel cv', max_length=2, verbose_name='language')),
            ],
            options={
                'verbose_name': 'resume',
                'verbose_name_plural': 'resumes',
                'db_table': 'resume',
            },
        ),
        migrations.CreateModel(
            name='ResumeEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begun_at', models.DateField(blank=True, help_text="Data iniziale dell'evento", null=True, verbose_name='begun_at')),
                ('ended_at', models.DateField(blank=True, help_text="Data finale dell'evento", null=True, verbose_name='ended_at')),
                ('title', models.CharField(help_text='Nome evento', max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='descrizione evento', null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'resume_event',
                'verbose_name_plural': 'resume_events',
                'db_table': 'resume_event',
                'ordering': ['-begun_at', '-ended_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nome sezione', max_length=255, unique=True, verbose_name='title')),
                ('description', tinymce.models.HTMLField(blank=True, help_text='descrizione sezione', null=True, verbose_name='description')),
                ('position', models.PositiveIntegerField(default=1, help_text="Posizione della sezione all'interno del cv", verbose_name='position')),
                ('resume', models.ForeignKey(help_text='Selezionare il cv nel quale inserire la sezione', on_delete=django.db.models.deletion.CASCADE, to='frontend.Resume', verbose_name='resume')),
            ],
            options={
                'verbose_name': 'resume_section',
                'verbose_name_plural': 'resume_sections',
                'db_table': 'resume_section',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.AddField(
            model_name='resumeevent',
            name='section',
            field=models.ForeignKey(help_text="Selezionare la sezione nella quale inserire l'evento", on_delete=django.db.models.deletion.CASCADE, to='frontend.ResumeSection', verbose_name='resume_event'),
        ),
        migrations.AlterUniqueTogether(
            name='resumesection',
            unique_together={('resume', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='resumeevent',
            unique_together={('section', 'title')},
        ),
    ]
