# Generated by Django 2.0.7 on 2021-05-02 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_it', models.TextField()),
                ('message_en', models.TextField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'board_item',
                'verbose_name': 'Voci bacheca',
            },
        ),
    ]
