# Generated by Django 2.0.7 on 2026-03-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_boarditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boarditem',
            options={'ordering': ['order'], 'verbose_name': 'Voce bacheca', 'verbose_name_plural': 'Voci bacheca'},
        ),
    ]
